# Generated by Django 4.0.3 on 2022-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.CharField(blank=True, max_length=200)),
                ('names', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('subtopics', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('grade', models.CharField(max_length=1000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
